[platformio]
default_envs = appA

[env:common]
platform        = espressif8266
board           = esp01_1m
framework       = arduino
upload_port     = /dev/cu.usbserial-1120
upload_speed    = 115200

[env:bootloader]
platform        = ${env:common.platform}
board           = ${env:common.board}
framework       = ${env:common.framework}
upload_port     = ${env:common.upload_port}
upload_speed    = ${env:common.upload_speed}
build_src_filter = +<bootloader/*>

[env:appA]
platform        = ${env:common.platform}
board           = ${env:common.board}
framework       = ${env:common.framework}
upload_port     = ${env:common.upload_port}
upload_speed    = ${env:common.upload_speed}
build_src_filter = +<appA/*>

[env:appB]
platform        = ${env:common.platform}
board           = ${env:common.board}
framework       = ${env:common.framework}
upload_port     = ${env:common.upload_port}
upload_speed    = ${env:common.upload_speed}
build_src_filter = +<appB/*>
